#!/usr/bin/python
# This file is part of the Hotwire Shell user interface.
#   
# Copyright (C) 2007 Colin Walters <walters@verbum.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys, os
if sys.version_info[0] < 2 or sys.version_info[1] < 5:
    try:
        os.execvp('python2.5', ['python2.5'] + sys.argv)
    except OSError, e:
        print >>sys.stderr, "Hotwire requires Python 2.5"
        os._exit(1) 

import logging, re, getopt

if __name__ == '__main__' and hasattr(sys.modules['__main__'], '__file__'):
    basedir = os.path.dirname(os.path.abspath(__file__))
    up_basedir = os.path.dirname(basedir)
    if os.path.basename(basedir) == 'ui':
        sys.path.insert(0, up_basedir)
import hotwire
import hotwire.sysdep
from hotwire.sysdep.fs import Filesystem
import hotwire.logutil
import hotwire.util
from hotwire.version import __version__, svn_version_str

_logger = logging.getLogger("hotwire.MimeOpenMain")

def usage():
    sys.stdout.write('Hotwire mimeopen %s %s\n' % (__version__, svn_version_str()))
    sys.stdout.write("%s [--debug] [--debug-modules=mod1,mod2...] [--help] FILENAME\n" % (sys.argv[0],))

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hdsn", ["help", "debug", "debug-modules=",])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    if len(args) != 1:
      sys.stderr.write('file name required\n')
      sys.exit(1)

    target_filename = args[0]

    debug = False
    debug_modules = []
    for o, v in opts:
        if o in ('-d', '--debug'):
            debug = True
        elif o in ('--debug-modules'):
            debug_modules = v.split(',')
        elif o in ("-h", "--help"):
            usage()
            sys.exit()

    default_log_level = logging.ERROR
    if debug:
        default_log_level = logging.DEBUG

    hotwire.logutil.init(default_log_level, debug_modules, 'hotwire.')

    fs = Filesystem.getInstance()
    fs.launch_edit_file(os.path.abspath(target_filename))

if __name__ == "__main__":
    main()
